name: toro_cheval
description: A Toro & Cheval game built with Flutter.
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0
  provider: ^6.1.0
  flutter_animate: ^4.0.0
  lottie: ^2.7.0
  animated_text_kit: ^4.2.2
  stop_watch_timer: ^3.0.2
  flutter_svg: ^2.0.9
  shared_preferences: ^2.2.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: false
  image_path: "images/tc_icon.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "images/tc_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
